In [1]:
# -------------------------------------------
# Notebook bootstrap (industry-standard)
# -------------------------------------------

import sys
from pathlib import Path

# project root = equity-fundamentals-analytics
PROJECT_ROOT = Path.cwd().parents[1]
SRC_PATH = PROJECT_ROOT / "src"

if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

print("SRC path added:", SRC_PATH)

SRC path added: c:\Users\dhira\Desktop\equity-analytics\equity-fundamentals-analytics\src

In [2]:
from equity_analytics.io import save_equity_df_std, load_equity_df_std
print("Import OK")

Import OK

#### **Import libraries**

In [3]:
import pandas as pd
import numpy as np

#### **Load the dataset (adjust filename if needed)**

In [4]:
# Path to the raw equity data CSV file
equity_data_path = "../../data/raw/equity_data.csv"

# Print the file path to verify that it's correct
print(equity_data_path)

../../data/raw/equity_data.csv

**# Read the CSV file into a pandas DataFrame**

In [5]:

raw_equity_df = pd.read_csv(equity_data_path)

raw_equity_df

,S.No.,Industries,Name,CMP Rs.,Mar Cap Rs.Cr.,Debt / Eq,Sales Rs.Cr.,Sales growth %,Sales Qtr Rs.Cr.,Profit growth %,Profit Var 5Yrs %,ROE %,OPM %,EPS 12M Rs.,PEG,P/E,PAT 12M Rs.Cr.,ROCE %,CMP / BV
0,1,Auto Components Companies,Samvardh. Mothe.,112.16,118389.50,0.53,117367.72,7.30,30172.97,-11.59,26.02,12.16,8.86,3.10,0.59,35.35,3348.88,13.66,3.19
1,2,Auto Components Companies,Bosch,36870.00,108780.78,0.01,18959.70,10.55,4794.80,13.42,12.76,15.55,13.11,909.18,2.61,47.89,2271.53,21.11,7.76
2,3,Auto Components Companies,Uno Minda,1305.10,75253.94,0.46,18015.43,17.14,4814.03,21.44,40.73,17.50,11.54,19.02,1.74,68.82,1093.46,18.83,12.08
3,4,Auto Components Companies,Bharat Forge,1446.20,69113.96,0.71,15268.83,-3.52,4031.93,3.89,20.51,11.58,17.66,22.54,80.94,63.94,1080.93,12.18,7.39
4,5,Auto Components Companies,MRF,153355.00,65066.94,0.19,29130.05,9.56,7378.72,-4.82,5.75,10.62,14.11,4370.73,0.70,35.10,1853.67,13.62,3.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3140,3141,Chemicals & Petrochemicals (battery chemicals),Energy InfrTrust,87.45,5806.68,7.16,3876.27,-7.20,1892.82,-68.79,15.31,0.46,38.24,1.33,-0.88,65.53,88.61,4.20,6.42
3141,3142,Chemicals & Petrochemicals (battery chemicals),Confidence Petro,40.54,1345.26,0.60,3717.08,37.24,983.01,33.35,11.63,7.24,9.05,2.83,34.93,14.32,93.96,9.33,0.98
3142,3143,Chemicals & Petrochemicals (battery chemicals),IRM Energy,311.35,1274.33,0.08,1040.55,15.97,259.44,-35.29,15.48,4.68,8.86,10.00,-1.02,31.03,41.07,8.26,1.32
3143,3144,Chemicals & Petrochemicals (battery chemicals),Kotyark Indust.,242.15,248.91,0.54,238.66,-29.91,147.32,-90.70,NaN,9.83,10.51,2.65,NaN,91.51,2.72,13.03,1.67
3144,3145,Chemicals & Petrochemicals (battery chemicals),Indifra Ltd,16.15,11.77,0.00,4.77,-74.84,2.60,-250.00,-34.02,0.06,-15.72,-0.53,NaN,NaN,-0.39,0.11,0.65

**# Display the first 5 rows of the dataset.**

In [6]:
# We use .head() to quickly inspect the structure of the data
# and confirm that it loaded correctly.
raw_equity_df.head()

,S.No.,Industries,Name,CMP Rs.,Mar Cap Rs.Cr.,Debt / Eq,Sales Rs.Cr.,Sales growth %,Sales Qtr Rs.Cr.,Profit growth %,Profit Var 5Yrs %,ROE %,OPM %,EPS 12M Rs.,PEG,P/E,PAT 12M Rs.Cr.,ROCE %,CMP / BV
0,1,Auto Components Companies,Samvardh. Mothe.,112.16,118389.50,0.53,117367.72,7.30,30172.97,-11.59,26.02,12.16,8.86,3.10,0.59,35.35,3348.88,13.66,3.19
1,2,Auto Components Companies,Bosch,36870.00,108780.78,0.01,18959.70,10.55,4794.80,13.42,12.76,15.55,13.11,909.18,2.61,47.89,2271.53,21.11,7.76
2,3,Auto Components Companies,Uno Minda,1305.10,75253.94,0.46,18015.43,17.14,4814.03,21.44,40.73,17.50,11.54,19.02,1.74,68.82,1093.46,18.83,12.08
3,4,Auto Components Companies,Bharat Forge,1446.20,69113.96,0.71,15268.83,-3.52,4031.93,3.89,20.51,11.58,17.66,22.54,80.94,63.94,1080.93,12.18,7.39
4,5,Auto Components Companies,MRF,153355.00,65066.94,0.19,29130.05,9.56,7378.72,-4.82,5.75,10.62,14.11,4370.73,0.70,35.10,1853.67,13.62,3.35

**# Show the number of rows and columns in the DataFrame.**

In [7]:
# Show the number of rows and columns in the DataFrame.
# .shape helps understand the dataset size (e.g., how many records we have).
raw_equity_df.shape

(3145, 19)

**# Display summary information about the DataFrame:**

In [8]:
# - column names
# - number of non-null values
# - data types
# - memory usage
# This helps identify missing data and understand the dataset's structure.
raw_equity_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3145 entries, 0 to 3144
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              3145 non-null   int64
 1   Industries         3145 non-null   object
 2   Name               3145 non-null   object
 3   CMP Rs.            3145 non-null   float64
 4   Mar Cap Rs.Cr.     3145 non-null   float64
 5   Debt / Eq          2971 non-null   float64
 6   Sales Rs.Cr.       3143 non-null   float64
 7   Sales growth %     2963 non-null   float64
 8   Sales Qtr Rs.Cr.   3136 non-null   float64
 9   Profit growth %    3088 non-null   float64
 10  Profit Var 5Yrs %  2300 non-null   float64
 11  ROE %              2920 non-null   float64
 12  OPM %              2989 non-null   float64
 13  EPS 12M Rs.        3127 non-null   float64
 14  PEG                2258 non-null   float64
 15  P/E                2506 non-null   float64
 16  PAT 12M Rs.Cr.     3143 non-null   float64
 17  ROCE %             3036 non-null   float64
 18  CMP / BV           2921 non-null   float64
dtypes: float64(16), int64(1), object(2)
memory usage: 467.0+ KB

**# Check for missing values in each column.**

In [9]:

# .isna() identifies NaN values,
# and .sum() counts how many NaNs each column contains.
raw_equity_df.isna().sum().sort_values(ascending=True)

S.No.                  0
Industries             0
Name                   0
CMP Rs.                0
Mar Cap Rs.Cr.         0
Sales Rs.Cr.           2
PAT 12M Rs.Cr.         2
Sales Qtr Rs.Cr.       9
EPS 12M Rs.           18
Profit growth %       57
ROCE %               109
OPM %                156
Debt / Eq            174
Sales growth %       182
CMP / BV             224
ROE %                225
P/E                  639
Profit Var 5Yrs %    845
PEG                  887
dtype: int64

**# Missing value percentages calculated**

In [10]:
# .isna() flags missing values as True,
# .mean() computes the proportion of True values (i.e., missing values),
# multiplying by 100 converts it to a percentage,
# and .round(2) formats the result to two decimal places.
# Option 1 (raw_equity_df.isna().mean() * 100).round(2).astype(str) + "%"

# Option 2 
(raw_equity_df.isna().mean() * 100). \
    sort_values(ascending=False). \
    map(lambda x: f"{x:.2f}%")

PEG                  28.20%
Profit Var 5Yrs %    26.87%
P/E                  20.32%
ROE %                 7.15%
CMP / BV              7.12%
Sales growth %        5.79%
Debt / Eq             5.53%
OPM %                 4.96%
ROCE %                3.47%
Profit growth %       1.81%
EPS 12M Rs.           0.57%
Sales Qtr Rs.Cr.      0.29%
Sales Rs.Cr.          0.06%
PAT 12M Rs.Cr.        0.06%
S.No.                 0.00%
Name                  0.00%
Industries            0.00%
Mar Cap Rs.Cr.        0.00%
CMP Rs.               0.00%
dtype: object

**# Missing value overview table created.**

In [11]:
# Create an overview of missing values for each column
missing_overview = (
    raw_equity_df
    # Step 1: Identify missing values (True for NaN, False otherwise)
    .isna()
    
    # Step 2: Count missing values per column
    .sum()
    
    # Step 3: Convert the missing counts into a DataFrame
    .to_frame(name="missing_count")
    
    # Step 4: Add a new column 'missing_pct' to calculate % missing
    .assign(
        missing_pct=lambda x: (
            (x["missing_count"] / len(raw_equity_df)) * 100
        ).round(2)
    )
    
    # Step 5: Keep only columns that actually have missing values
    .query("missing_count > 0")
    
    # Step 6: Sort by missing percentage (highest first)
    .sort_values("missing_pct", ascending=False)
)

# Display the missing values overview table
missing_overview

                   missing_count  missing_pct
PEG                          887        28.20
Profit Var 5Yrs %            845        26.87
P/E                          639        20.32
ROE %                        225         7.15
CMP / BV                     224         7.12
Sales growth %               182         5.79
Debt / Eq                    174         5.53
OPM %                        156         4.96
ROCE %                       109         3.47
Profit growth %               57         1.81
EPS 12M Rs.                   18         0.57
Sales Qtr Rs.Cr.               9         0.29
Sales Rs.Cr.                   2         0.06
PAT 12M Rs.Cr.                 2         0.06

**# Count the number of duplicate rows in the DataFrame.**

In [12]:
# .duplicated() identifies rows that exactly match a previous row (True = duplicate),
# and .sum() counts how many duplicates there are.
raw_equity_df.duplicated().sum()

np.int64(0)

**# Extract the column names from the DataFrame and convert them into a Python list.**

In [13]:
# This is useful when you need to loop through columns,
# select specific columns, or inspect the structure of the dataset.
columns = list(raw_equity_df)

# Display the list of column names
columns

['S.No.',
 'Industries',
 'Name',
 'CMP\xa0Rs.',
 'Mar Cap\xa0Rs.Cr.\xa0',
 'Debt / Eq',
 'Sales\xa0Rs.Cr.',
 'Sales growth\xa0%',
 'Sales Qtr\xa0Rs.Cr.',
 'Profit growth\xa0%',
 'Profit Var 5Yrs\xa0%',
 'ROE\xa0%',
 'OPM\xa0%',
 'EPS 12M\xa0Rs.',
 'PEG',
 'P/E',
 'PAT 12M\xa0Rs.Cr.',
 'ROCE\xa0%',
 'CMP / BV']

**# Column classification (analysis only)**

In [14]:
column_classification ={
    "identifier":[
        "S.No.",
        "Name"
    ],
    "categorical":[
        "industries"
    ],
    "numeric_raw":[
        "CMP Rs.",
        "Mar Cap Rs.Cr.",
        "Sales Rs.Cr",
        "Sales QTR Rs.Cr.",
        "PAT 12M Rs.Cr",
        "EPS 12M Rs."
    ],
    "derived_ratio":[
        "Debt / Eq",
        "Sales growth %",
        "Profit growth %",
        "Profit Var 5Yrs %",
        "ROE %",
        "ROCE %",
        "OPM %",
        "P/E",
        "PEG",
        "CMP / BV"
    ]

}

column_classification

{'identifier': ['S.No.', 'Name'],
 'categorical': ['industries'],
 'numeric_raw': ['CMP Rs.',
  'Mar Cap Rs.Cr.',
  'Sales Rs.Cr',
  'Sales QTR Rs.Cr.',
  'PAT 12M Rs.Cr',
  'EPS 12M Rs.'],
 'derived_ratio': ['Debt / Eq',
  'Sales growth %',
  'Profit growth %',
  'Profit Var 5Yrs %',
  'ROE %',
  'ROCE %',
  'OPM %',
  'P/E',
  'PEG',
  'CMP / BV']}

**# Validate data types**

In [15]:
raw_equity_df.dtypes

S.No.                  int64
Industries            object
Name                  object
CMP Rs.              float64
Mar Cap Rs.Cr.       float64
Debt / Eq            float64
Sales Rs.Cr.         float64
Sales growth %       float64
Sales Qtr Rs.Cr.     float64
Profit growth %      float64
Profit Var 5Yrs %    float64
ROE %                float64
OPM %                float64
EPS 12M Rs.          float64
PEG                  float64
P/E                  float64
PAT 12M Rs.Cr.       float64
ROCE %               float64
CMP / BV             float64
dtype: object

#### **Data Cleaning Strategy (Design Phase)**

#### **1️⃣ Core Principle**

- Cleaning will be business-aware, conservative, and reversible.
- No column will be altered without a clear financial justification.

#### **2️⃣ Column-wise Cleaning Strategy**
🔹 Identifier Columns

**Columns: S.No., Name**

 - Must never be null
 - No filling, no transformation
 - Used only for identification
 - Any null here would be treated as a data quality error

**Action:**

➡ Keep as-is

➡ Validate only

---

#### **🔹 Categorical Columns**

**Columns:** Industries

 - Used for grouping and segmentation
 - Missing values may indicate unclassified companies

**Action:**

➡ Keep missing as NaN

➡ No imputation at this stage

➡ Consider “Unknown” only if required later (EPIC 4)

---

#### **🔹 Numeric Raw Columns (Absolute Business Facts)**

**Columns:**
CMP Rs., Mar Cap Rs.Cr., Sales Rs.Cr., Sales Qtr Rs.Cr.,
PAT 12M Rs.Cr., EPS 12M Rs.

- Represent absolute financial values
- Missing values usually due to reporting lag

**Action:**

➡ Do NOT fill with mean/median

➡ Keep missing as NaN

➡ Exclude rows only when metric is required (conditional filtering)

---

#### **3️⃣ Column Name Standardization Rules (Preview)**

- Convert to lowercase
- Replace spaces with _
- Replace % with _pct
- Remove special characters
- No semantic changes

(Actual renaming will happen in Task 2.2)

---

#### **4️⃣ Validation Rules (Post-cleaning)**

 - Row count must remain unchanged (unless explicitly filtered)
 - No identifier column becomes null
 - Numeric columns remain numeric
 - Derived metrics retain original meaning

 ---

#### **🚫 Explicitly Out of Scope (Task 2.1)**

 - No missing value filling
 - No column renaming
 - No row dropping
 - No recalculations

#### **Create Column Rename Mapping**

In [16]:
# -------------------------------------------
# Column Rename Mapping
# -------------------------------------------

column_rename_map = {
    "S.No.": "s_no",
    "Industries": "industry",
    "Name": "company_name",
    "CMP Rs.": "cmp_rs",
    "Mar Cap Rs.Cr.": "market_cap_cr",
    "Sales Rs.Cr.": "sales_cr",
    "Sales Qtr Rs.Cr.": "sales_qtr_cr",
    "Sales growth %": "sales_growth_pct",
    "PAT 12M Rs.Cr.": "pat_12m_cr",
    "Profit growth %": "profit_growth_pct",
    "Profit Var 5Yrs %": "profit_var_5yrs_pct",
    "ROE %": "roe_pct",
    "ROCE %": "roce_pct",
    "OPM %": "opm_pct",
    "EPS 12M Rs.": "eps_12m_rs",
    "Debt / Eq": "debt_to_eq",
    "PEG": "peg",
    "P/E": "pe",
    "CMP / BV": "cmp_to_bv"
}

column_rename_map

{'S.No.': 's_no',
 'Industries': 'industry',
 'Name': 'company_name',
 'CMP Rs.': 'cmp_rs',
 'Mar Cap Rs.Cr.': 'market_cap_cr',
 'Sales Rs.Cr.': 'sales_cr',
 'Sales Qtr Rs.Cr.': 'sales_qtr_cr',
 'Sales growth %': 'sales_growth_pct',
 'PAT 12M Rs.Cr.': 'pat_12m_cr',
 'Profit growth %': 'profit_growth_pct',
 'Profit Var 5Yrs %': 'profit_var_5yrs_pct',
 'ROE %': 'roe_pct',
 'ROCE %': 'roce_pct',
 'OPM %': 'opm_pct',
 'EPS 12M Rs.': 'eps_12m_rs',
 'Debt / Eq': 'debt_to_eq',
 'PEG': 'peg',
 'P/E': 'pe',
 'CMP / BV': 'cmp_to_bv'}

#### **Apply column renaming (safe copy)**

- Deep copy: Changes made to the new "copy" won't affect the original data (since it's completely independent).
- Shallow copy: Changes made to the new "copy" will affect the original data too (since it's just a reference).

In [17]:
# Rename the columns of the dataframe using the provided mapping and create a deep copy
equity_df = raw_equity_df.rename(columns=column_rename_map).copy()  

# Return the updated dataframe
equity_df.columns.tolist()

['s_no',
 'industry',
 'company_name',
 'CMP\xa0Rs.',
 'Mar Cap\xa0Rs.Cr.\xa0',
 'debt_to_eq',
 'Sales\xa0Rs.Cr.',
 'Sales growth\xa0%',
 'Sales Qtr\xa0Rs.Cr.',
 'Profit growth\xa0%',
 'Profit Var 5Yrs\xa0%',
 'ROE\xa0%',
 'OPM\xa0%',
 'EPS 12M\xa0Rs.',
 'peg',
 'pe',
 'PAT 12M\xa0Rs.Cr.',
 'ROCE\xa0%',
 'cmp_to_bv']

#### **Missing value baseline after column renaming**

In [18]:
# Count missing values per column
missing_counts_post_rename = equity_df.isna().sum()

# Convert to DataFrame for readability
# Convert 'missing_counts_post_rename' into a DataFrame with a new column 'missing_count'
missing_summary_post_rename = (
    missing_counts_post_rename
    .to_frame(name="missing_count")  # Convert series to DataFrame and rename the column
    .assign(
        # Calculate the percentage of missing data for each entry, round to 2 decimal places
        missing_pct=lambda x: (x["missing_count"] / len(equity_df) * 100).round(2)
    )
    .query("missing_count > 0")  # Filter rows where there are missing values (i.e., 'missing_count' > 0)
    .sort_values("missing_pct", ascending=False)  # Sort the rows by 'missing_pct' in descending order
)

# Display the final DataFrame with the missing counts and their corresponding percentages
missing_summary_post_rename

                   missing_count  missing_pct
peg                          887        28.20
Profit Var 5Yrs %            845        26.87
pe                           639        20.32
ROE %                        225         7.15
cmp_to_bv                    224         7.12
Sales growth %               182         5.79
debt_to_eq                   174         5.53
OPM %                        156         4.96
ROCE %                       109         3.47
Profit growth %               57         1.81
EPS 12M Rs.                   18         0.57
Sales Qtr Rs.Cr.               9         0.29
Sales Rs.Cr.                   2         0.06
PAT 12M Rs.Cr.                 2         0.06

#### **Identifier column missing value validation**

In [19]:
# -------------------------------------------
# Identifier column missing value validation
# -------------------------------------------

# Define the list of identifier columns to check for missing values
identifier_cols = ["s_no", "company_name"]

# Check for missing values in the specified identifier columns
# This will return the sum of missing (NaN) values for each identifier column
equity_df[identifier_cols].isna().sum()

s_no            0
company_name    0
dtype: int64

#### **Categorical column missing value validation**

In [20]:
# Define the list of categorical columns to check for missing values
categorical_cols = ["industry"]

# Check for missing values in the specified categorical column
# This will return the sum of missing (NaN) values for the 'industry' column
equity_df[categorical_cols].isna().sum()

industry    0
dtype: int64

#### **Inspect the actual column name after renaming**

In [21]:
equity_df.columns.tolist()

['s_no',
 'industry',
 'company_name',
 'CMP\xa0Rs.',
 'Mar Cap\xa0Rs.Cr.\xa0',
 'debt_to_eq',
 'Sales\xa0Rs.Cr.',
 'Sales growth\xa0%',
 'Sales Qtr\xa0Rs.Cr.',
 'Profit growth\xa0%',
 'Profit Var 5Yrs\xa0%',
 'ROE\xa0%',
 'OPM\xa0%',
 'EPS 12M\xa0Rs.',
 'peg',
 'pe',
 'PAT 12M\xa0Rs.Cr.',
 'ROCE\xa0%',
 'cmp_to_bv']

#### **Normalize column headers (remove hidden spaces)**

In [22]:
# Replace non-breaking spaces (represented as '\xa0') in column names with a regular space
equity_df.columns = equity_df.columns.str.replace("\xa0", " ", regex=False)

# Remove any leading or trailing whitespace characters from each column name
equity_df.columns = equity_df.columns.str.strip()

# Convert the cleaned column names to a list and return it
equity_df.columns.tolist()

['s_no',
 'industry',
 'company_name',
 'CMP Rs.',
 'Mar Cap Rs.Cr.',
 'debt_to_eq',
 'Sales Rs.Cr.',
 'Sales growth %',
 'Sales Qtr Rs.Cr.',
 'Profit growth %',
 'Profit Var 5Yrs %',
 'ROE %',
 'OPM %',
 'EPS 12M Rs.',
 'peg',
 'pe',
 'PAT 12M Rs.Cr.',
 'ROCE %',
 'cmp_to_bv']

#### **Re-apply rename mapping after header normalization**

In [23]:
# Create a fully standardized dataframe after cleaning column headers
equity_df_std = equity_df.rename(columns=column_rename_map).copy()

# Preview columns to confirm standardization
equity_df_std.columns.tolist()

['s_no',
 'industry',
 'company_name',
 'cmp_rs',
 'market_cap_cr',
 'debt_to_eq',
 'sales_cr',
 'sales_growth_pct',
 'sales_qtr_cr',
 'profit_growth_pct',
 'profit_var_5yrs_pct',
 'roe_pct',
 'opm_pct',
 'eps_12m_rs',
 'peg',
 'pe',
 'pat_12m_cr',
 'roce_pct',
 'cmp_to_bv']

#### **Numeric raw columns: identify missing values**

In [24]:
# Numeric raw (absolute business facts)
numeric_raw_cols = [
    "cmp_rs",
    "market_cap_cr",
    "sales_cr",
    "sales_qtr_cr",
    "pat_12m_cr",
    "eps_12m_rs"
]

# Missing counts for numeric raw columns (highest first)
equity_df_std[numeric_raw_cols].isna().sum().sort_values(ascending=False)

eps_12m_rs       18
sales_qtr_cr      9
sales_cr          2
pat_12m_cr        2
market_cap_cr     0
cmp_rs            0
dtype: int64

#### **Derived / ratio columns: identify missing values**

In [25]:
derived_ratio_cols = [
    "sales_growth_pct",
    "profit_growth_pct",
    "profit_var_5yrs_pct",
    "roe_pct",
    "roce_pct",
    "opm_pct",
    "pe",
    "peg",
    "debt_to_eq",
    "cmp_to_bv"
]

# Missing counts for derived/ratio columns
equity_df_std[derived_ratio_cols].isna().sum().sort_values(ascending=False)

peg                    887
profit_var_5yrs_pct    845
pe                     639
roe_pct                225
cmp_to_bv              224
sales_growth_pct       182
debt_to_eq             174
opm_pct                156
roce_pct               109
profit_growth_pct       57
dtype: int64

In [26]:
# -------------------------------------------
# Persist cleaned & standardized dataset
# -------------------------------------------

from equity_analytics.io import save_equity_df_std

output_path = save_equity_df_std(equity_df_std)
print(f"Saved cleaned dataset to: {output_path}")

Saved cleaned dataset to: data\processed\equity_df_std.csv